import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Providers from "./providers";
import Footer from "../components/layouts/footer/Footer";
import HeaderWrapper from "../components/layouts/header/HeaderWrapper";
import ChatBotFlotante from "../components/ChatBotFlotante";
import { Toaster } from "sonner";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout(props: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="es" className="light" style={{ colorScheme: "light" }}>
      <body className={inter.className}>
        <Providers>
          <HeaderWrapper />
          <main>{props.children}</main>
          <Footer />
          <ChatBotFlotante />
          <Toaster
            position="bottom-right"
            toastOptions={{
              style: {
                background: "#0a0a0a",
                border: "1px solid #00ffff40",
                color: "#ffffff",
                boxShadow: "0 0 15px #00ffff30",
                fontFamily: "inherit",
              },
              classNames: {
                success: "!border-[#00ffff60] !shadow-[0_0_15px_#00ffff40]",
                error: "!border-[#ff005560] !shadow-[0_0_15px_#ff005540]",
                actionButton:
                  "!bg-[#00ffff] !text-black !font-bold hover:!bg-[#00dddd]",
              },
            }}
          />
        </Providers>
      </body>
    </html>
  );
}
